language: python
python:
    - "2.7"
sudo: required
dist: trusty
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/Autonetwork/Autonetwork/ INTERFACE=SPI
    - PLATFORMIO_CI_SRC=examples/Blink/Blink/ INTERFACE=SPI
    - PLATFORMIO_CI_SRC=examples/Console/Console/ INTERFACE=SPI
    - PLATFORMIO_CI_SRC=examples/MQTT/MQTT/ INTERFACE=SPI
    - PLATFORMIO_CI_SRC=examples/Autonetwork/Autonetwork/ INTERFACE=UART
    - PLATFORMIO_CI_SRC=examples/Blink/Blink/ INTERFACE=UART
    - PLATFORMIO_CI_SRC=examples/Console/Console/ INTERFACE=UART
    - PLATFORMIO_CI_SRC=examples/MQTT/MQTT/ INTERFACE=UART
matrix:
    allow_failures:
        - env: PLATFORMIO_CI_SRC=examples/Autonetwork/Autonetwork/ INTERFACE=SPI
        - env: PLATFORMIO_CI_SRC=examples/Console/Console/ INTERFACE=SPI
        - env: PLATFORMIO_CI_SRC=examples/MQTT/MQTT/ INTERFACE=SPI
        - env: PLATFORMIO_CI_SRC=examples/Autonetwork/Autonetwork/ INTERFACE=UART
        - env: PLATFORMIO_CI_SRC=examples/Blink/Blink/ INTERFACE=UART
        - env: PLATFORMIO_CI_SRC=examples/Console/Console/ INTERFACE=UART
        - env: PLATFORMIO_CI_SRC=examples/MQTT/MQTT/ INTERFACE=UART
install:
    - pip install -U platformio
    - platformio lib -g install TimerOne DueTimer PubSubClient 872
    # Tmp fix for Microchip gcc-pic32
    - sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0
    - if [[ "$INTERFACE" == "UART" ]]; then sed -i "s/#define __SPI_INTERFACE__/\/\/#define __SPI_INTERFACE__/" src/dpa_library.h; fi
    - if [[ "$INTERFACE" == "UART" ]]; then sed -i "s/\/\/#define __UART_INTERFACE__/#define __UART_INTERFACE__/" src/dpa_library.h; fi
script:
    - if [[ "$PLATFORMIO_CI_SRC" == "examples/Autonetwork/Autonetwork/" ]]; then platformio ci --lib="." --project-conf examples/Autonetwork/platformio.ini; fi
    - if [[ "$PLATFORMIO_CI_SRC" == "examples/Blink/Blink/" ]]; then platformio ci --lib="." --project-conf examples/Blink/platformio.ini; fi
    - if [[ "$PLATFORMIO_CI_SRC" == "examples/Console/Console/" ]]; then platformio ci --lib="." --project-conf examples/Console/platformio.ini; fi
    - if [[ "$PLATFORMIO_CI_SRC" == "examples/MQTT/MQTT/" ]]; then platformio ci --lib="." --project-conf examples/MQTT/platformio.ini; fi
